# 1. Fase de Inventario (Descubrimiento Total)
- name: "Fase 1: Descubrimiento de Nodos para el Espejo"
  hosts: localhost
  connection: local
  tasks:
    - name: "Leer contrato maestro"
      include_vars:
        file: "../../lab-state.yaml"
        name: contrato

    - name: "Poblar inventario dinámico"
      add_host:
        name: "{{ item.nombre }}"
        # Clasificamos para que el monitor sepa a quién "scrapear"
        groups: "{{ 'eve_monitor_group' if item.nombre == 'eve-monitor' else 'targets_to_monitor' }}"
        ansible_host: "{{ item.red.ip.split('/')[0] }}"
        ansible_user: "root"
        ansible_ssh_private_key_file: "~/.ssh/eve_admin"
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
      loop: "{{ contrato.entornos }}"
      when: item.estado == 'presente' and item.tipo in ['vm', 'lxc']

# 2. Fase de Configuración Real
- name: "Fase 2.6: Configuración del Espejo (Observabilidad)"
  hosts: eve-monitor
  become: yes
  gather_facts: true

  tasks:
    - name: "1. Instalar VictoriaMetrics y Grafana en Alpine"
      community.general.apk:
        name: 
          - victoria-metrics
          - grafana
        update_cache: yes
        state: present

    - name: "2. Asegurar directorio de datos en el HDD (Mountpoint)"
      ansible.builtin.file:
        path: /var/lib/victoria-metrics
        state: directory
        # Cambiamos a root para que no falle el lookup, 
        # el binario de VictoriaMetrics hará el resto al arrancar
        owner: root 
        group: root
        mode: '0755'

    - name: "3. Generar Configuración de Auto-Discovery (Jinja2)"
      ansible.builtin.template:
        src: victoria-metrics-opts.j2
        dest: /etc/conf.d/victoria-metrics
      notify: Restart VictoriaMetrics

    - name: "4. Inyectar Password de Grafana desde SOPS"
      ansible.builtin.lineinfile:
        path: /etc/grafana/grafana.ini
        regexp: '^;admin_password ='
        line: "admin_password = {{ grafana_admin_password }}"
      no_log: true # Por seguridad no mostramos el pass en el log

    - name: "5. Iniciar Servicios"
      ansible.builtin.service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - victoria-metrics
        - grafana

  handlers:
    - name: Restart VictoriaMetrics
      ansible.builtin.service:
        name: victoria-metrics
        state: restarted

